- name: Ensure production instance is running and inventory is updated
  hosts: localhost
  gather_facts: no
  vars:
    instance_name: RunCalc_Prod
    region: us-east-1
    group: ec2_staging

  tasks:
    - name: Gather facts to check if the production instance already exists
      ec2_instance_info:
        region: "{{ region }}"
        filters:
          instance-state-name: running
          tag:Name: "{{ instance_name }}"
      register: ec2_exists

    - name: Fail if no running instances are found
      fail:
        msg: "No running production instances found."
      when: ec2_exists.instances | length == 0

    - name: Update inventory with dynamic public IPs
      add_host:
        name: "{{ item.public_ip_address }}"
        groups: "{{ group }}"
      loop: "{{ ec2_exists.instances }}"
      when: item.public_ip_address is defined

- name: Deploy Application on Production Instance
  vars:
    remote_ec2_user: ubuntu
    group: ec2_staging
    image_name: oku123xx/runcalc-pro
  hosts: "{{ group }}"
  remote_user: "{{ remote_ec2_user }}"
  become: yes

  tasks:
    - name: Stop existing container if it exists
      shell: docker stop runcalc || true

    - name: Remove existing container if it exists
      shell: docker rm runcalc || true

    - name: Pull selected image tag
      shell: docker pull {{ image_name }}:{{ image_tag }}

    - name: Run container on port 80
      shell: docker run -d --name runcalc -p 80:80 {{ image_name }}:{{ image_tag }}